// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS3Yzzrp1COn6Se0_Z8fqojqk5VJ7Bmfg',
    appId: '1:565424510027:web:47827e6e8cf0020b1c29ce',
    messagingSenderId: '565424510027',
    projectId: 'scouts-5',
    authDomain: 'scouts-5.firebaseapp.com',
    storageBucket: 'scouts-5.appspot.com',
    measurementId: 'G-WR906J9M6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBO2D1GVou8gqTgXzY4uHtgLd5EUNLuQE',
    appId: '1:565424510027:android:65806da501f0d9d61c29ce',
    messagingSenderId: '565424510027',
    projectId: 'scouts-5',
    storageBucket: 'scouts-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE255PBjrowV3zwOaM_FcPTuXIF5Q4V9g',
    appId: '1:565424510027:ios:4e5a0d7cdb09e1f41c29ce',
    messagingSenderId: '565424510027',
    projectId: 'scouts-5',
    storageBucket: 'scouts-5.appspot.com',
    iosBundleId: 'com.example.sgwenScouts5',
  );
}
